#!/usr/bin/env bash

# Kill all running polybar instances
killall -q polybar
# Wait for them to quit
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
    MONITOR=$m polybar --reload example &
done

echo "Starting Polybar"

