tap "1password/tap"
tap "boz/repo"
tap "hashicorp/tap"
tap "homebrew/bundle"
tap "homebrew/services"
tap "koekeishiya/formulae"
tap "oven-sh/bun"
brew "awscli"
brew "bat"
brew "btop"
brew "gnutls"
brew "leptonica"
brew "tesseract"
brew "ffmpeg"
brew "fnm"
brew "fzf"
brew "gh"
brew "git"
brew "glow"
brew "gnupg"
brew "go"
brew "gping"
brew "helm"
brew "htop"
brew "imagemagick"
brew "ipmitool"
brew "jq"
brew "kubernetes-cli"
brew "kubectx"
brew "mas"
brew "minicom"
brew "mtr"
brew "ncdu"
brew "neofetch"
brew "neovim"
brew "nmap"
brew "oha"
brew "openssl@1.1"
brew "pinentry-mac"
brew "pssh"
brew "rclone"
brew "ripgrep"
brew "shodan"
brew "stow"
brew "telnet"
brew "tmux"
brew "watch"
brew "yt-dlp"
brew "hashicorp/tap/packer"
brew "koekeishiya/formulae/skhd"
brew "oven-sh/bun/bun"
cask "1password-cli"
cask "kitty"
cask "nrlquaker-winbox"
cask "orbstack"
mas "Keynote", id: 409183694
mas "LightBlue", id: 557428110
mas "Medis", id: 1579200037
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Parcel", id: 639968404
mas "Sleep Control Center", id: 946798523
mas "Speedtest", id: 1153157709
mas "Telegram Lite", id: 946399090
mas "WireGuard", id: 1451685025
mas "Wondershare PDFelement", id: 1470732135
