#!/usr/bin/env zsh
export STOW_FOLDERS="nvim,scripts,skhd,tmux,zsh,ghostty,zed";

for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
  stow -D $folder
  stow -t $HOME $folder
done

stow -t $HOME git
